### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by faithpaddy** [SaiAshish-Konchada/Python-Projects-for-Beginners#1]
pls concerning the alarm clock ,my code shows an error saying break is outside the loop. 
![Screenshot (227)](https://user-images.githubusercontent.com/105517298/168933209-32c9d99a-857a-4b2c-b76b-5f65bdfc624d.png)
pls how can i resolve it

**Comment by faithpaddy** [comment]
pls any help

**Comment by SaiAshish-Konchada** [comment]
> pls any help
> pls concerning the alarm clock ,my code shows an error saying break is outside the loop. ![Screenshot (227)](https://user-images.githubusercontent.com/105517298/168933209-32c9d99a-857a-4b2c-b76b-5f65bdfc624d.png) pls how can i resolve it

The statements inside the loop lack indentation(proper spacing). Align the code as seen here:
![image](https://user-images.githubusercontent.com/51746934/169257645-49ba61bd-1991-4e2e-84bf-aeec0664b522.png)

Also, provide a path to a sound/music file you want to play when the alarm rings.
